### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by DustinSnijders** [F5OEO/rpidatv#12]
I'm trying to install your software on a clean Raspberry Pie 1B with the latest edition of Rasbian. I'm sure i do something wrong due to the fact that there is no signal-out after these steps:

1. deploy Rasbian lite image to Pi (last version)
2. expand memory via raspi-config
3. these commando's:

sudo apt-get update && 
sudo apt-get install rpi-update && 
sudo rpi-update && 
sudo apt-get install apt-transport-https && 
sudo apt-get install git && 
git clone git://github.com/f5oeo/rpidatv && 
cd rpidatv/src && 
make -j 4

Do i forget something? Do I something wrong? (NB. I had exactly the same results with a Pi 3B, so i'm quite sure I do something wrong)

Cheers,
Dustin

**Comment by F5OEO** [comment]
you can then launch ./scripts/gbmenu.sh

**Comment by F5OEO** [comment]
Need to write a basic startup on wiki
