### ISSUE TITLE
leandvb2video.sh not working

### ISSUE THREAD

**Issue by mikerobertsn** [F5OEO/rpidatv#15]
After installing everything as per the instructions the error below presented itself when trying to run leandvb2video.sh

./leandvb2video.sh: line 25: let: 437.5: syntax error: invalid arithmetic operator (error token is ".5")
leandvb: no process found
mplayer: no process found
mkfifo: cannot create fifo ‘fifots’: File exists

**Comment by F5OEO** [comment]
Fixed with commit : https://github.com/F5OEO/rpidatv/commit/14773f5299543185abc6fcebaaeb33a450b6ad04
