### ISSUE TITLE
/leandvb2video.sh still not ok for me

### ISSUE THREAD

**Issue by weddy2015** [F5OEO/rpidatv#16]
pi@raspberrypi:~/rpidatv $ ./scripts/leandvb2video.sh
Freq = 437500000
leandvb: no process found
mplayer: no process found
mkfifo: cannot create fifo ‘fifots’: File exists

from menu i got
/home/pi/rpidatv/scripts/menu.sh: line 459: let: 437.5: syntax error: invalid arithmetic operator (error token is ".5")
receive on 250000 at Frequency
mkfifo: cannot create fifo ‘fifots’: File exists

MPlayer interrupted by signal 15 in module: demux_open
Cannot seek backward in linear streams!
Seek failed

 after the update still not running.

Edwin

**Comment by SopaXorzTaker** [comment]
Try installing VLC and replacing mplayer with it in script.

**Comment by F5OEO** [comment]
Sure to run it on jessie ?
