### ISSUE TITLE
Cannot stream RPi Camera

### ISSUE THREAD

**Issue by trishmapow** [F5OEO/rpidatv#18]
Hi, I have seen demonstrations where a camera stream is used. I have a Raspberry Pi camera and would like to stream this. What is the command required?
So far, I have tried to broadcast sample picture in /video but VLC doesn't play anything when I use:
`sudo rtl_sdr -f 437500000 -s 2400000 - | ./leandvb --gui | vlc -`

**Comment by SopaXorzTaker** [comment]
Does leandvb show 4 bold, unconnected dots in the PSK symbols window? If not, you need to provide it the right symbol rate
