### ISSUE TITLE
leandvb2video.sh kills nonexistent processes

### ISSUE THREAD

**Issue by syelnmh** [F5OEO/rpidatv#23]
rpidatv/scripts/leandvb2video.sh: lines 34 - 36
```
sudo killall leandvb
sudo killall mplayer
mkfifo fifots
```
Should check whether leandvb and mplayer are running before killing. Generates unnecessary error messages when they aren't. Same with mkfifo fifots, check if fifots exists first. Also, might want to change the name 'fifots'  to something less "generic".

**Comment by F5OEO** [comment]
Agree..but more warning than errors. Less priority
