### ISSUE TITLE
mplayer vs VLC

### ISSUE THREAD

**Issue by syelnmh** [F5OEO/rpidatv#24]
mplayer just doesn't work on the raspberry pi (lirc troubles, amongst others). Using newest raspbian jessie (May 2016), downloaded yesterday. Swapping mplayer for VLC at least opens the VLC window with fifots in the header bar.
Either way, no video on receive.

**Comment by F5OEO** [comment]
mplayer was used because of capabilitie to display on FrameBuffer for Touchscreen. Tested on Jessie. Welcome to present other solution
