### ISSUE TITLE
Synchronization error with Raspberry pi B+

### ISSUE THREAD

**Issue by csarmo** [F5OEO/rpidatv#27]
Hello F5OE0. I'm new using the Rapsberry. I trying to stream the file attached to your code "mire.jpg" using the console command ./rpidatv.... The thing is after i execute the command a lot of SYNC ERROR appear. "ladecadence" commented on 25 May about this issue. I tried the solution you gave him, I also put the Raspberry in Turbo Mode using the raspi-config and the error continues. I'm using the last Raspian distribution updated and the Model B+. If you could please provide me another solution to this issue. I just have this raspberry pi model so i'm trying to look for any solution instead of just change it to a newer faster model.

**Comment by F5OEO** [comment]
See my comment : https://github.com/F5OEO/rpidatv/issues/22#issuecomment-238217722
