### ISSUE TITLE
g++ issue in "-03" option

### ISSUE THREAD

**Issue by csarmo** [F5OEO/rpidatv#30]
I have problems with this line 
g++ -O3 -DGUI leandvb.cc -lX11 -o leandvb
it guives me an error: unknown option "-03"
i follow all the options in order to install leandvb but this is the line that stop the progress.

**Comment by SopaXorzTaker** [comment]
It is -O3, not -03. And also, why couldn't you just copy and paste this command?

**Comment by csarmo** [comment]
Ok. I was writing the entire line instead of copying. Thanks.
