### ISSUE TITLE
avc2ts installation fail

### ISSUE THREAD

**Issue by csarmo** [F5OEO/rpidatv#42]
When i try to make the compilation of the code it guives me the next error:

Compilation terminated.
Makefile:17: recipe for target 'vncclient.o' failed
make: *** [vnclient.o] Error 1

I don't know what is the recipe i'm missing.

**Comment by F5OEO** [comment]
You should install libvncserver-dev package prior to compile

**Comment by csarmo** [comment]
Yeah, that was the lib i was missing. Thanks.
