### ISSUE TITLE
scripts pointing to /home/pi

### ISSUE THREAD

**Issue by michelinok** [F5OEO/rpidatv#6]
All the scripts points to /home/pi/....
I think it's wrong and should not use absolute paths, instead i would use ../ or something similar.

**Comment by F5OEO** [comment]
You are right...should be corrected but have to use abolute path for launching from anywhere (at rc-local.md for example)

**Comment by SopaXorzTaker** [comment]
Idea, maybe autogenerate the scripts from templates inserting the proper paths?

**Comment by F5OEO** [comment]
@SopaXorzTaker Thanks in efforts, have to accept pull request by hand. Not enough confident with git to do that right now, sorry. Accept it if on latest commit.
